version: "2"
services:
  php:
    container_name: docker_php
    build: .docker/php
    volumes:
      - /Users/apple/Desktop/DevWeb/Projets-Formation/JAVA_SQL_DOCKER_INIT-main-3/www:/home/wwwroot

  #  apache:
  #    container_name: docker_apache
  #    build: .docker/apache
  #    ports:
  #      - "8080:80"
  #    volumes:
  #      - .:/home/wwwroot
  #    depends_on:
  #      - php

  db:
    build: .docker/db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    container_name: docker_mysql
    restart: always
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
